In [14]:
import pandas as pd
import geopy.distance

In [2]:
pip install geopy

Requirement already satisfied: geopy in c:\users\vowel\anaconda3\envs\pythondata\lib\site-packages (2.2.0)
Requirement already satisfied: geographiclib<2,>=1.49 in c:\users\vowel\anaconda3\envs\pythondata\lib\site-packages (from geopy) (1.52)
Note: you may need to restart the kernel to use updated packages.

In [3]:
auto_part_theft = pd.read_csv(r"C:\Users\vowel\Desktop\auto_part_theft.csv")
auto_part_theft.head()

,incident_id,offense_id,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,address,GEO_X,GEO_Y,lon,lat,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,20223421,2.022340e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/3/2022 0:00,NaN,1/3/2022 10:47,4055 N ALBION ST ...,3157680,1707127,-104.939033,39.773534,2,221,northeast-park-hill,1,0
1,20226000117,2.022600e+16,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/3/2022 0:20,1/3/2022 14:20,1/3/2022 14:32,25 E 16TH AVE ...,3144402,1695493,-104.986504,39.741812,6,621,north-capitol-hill,1,0
2,20226673,2.022670e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/4/2022 18:00,1/5/2022 11:26,1/5/2022 11:26,2401 E 40TH AVE ...,3152270,1706837,-104.958285,39.772828,2,212,clayton,1,0
3,20228679,2.022870e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/2/2022 22:00,1/3/2022 8:00,1/6/2022 16:54,E 35TH AVE / N ALBION ST ...,3157620,1704248,-104.939309,39.765632,2,221,northeast-park-hill,1,0
4,20225711,2.022570e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/4/2022 6:40,1/4/2022 18:14,1/4/2022 19:15,1830 N FRANKLIN ST ...,3149529,1696797,-104.968245,39.745311,6,622,city-park-west,1,0

In [4]:
auto_repair = pd.read_csv(r"C:\Users\vowel\Desktop\auto_repair.csv")
auto_repair.head()

,Unnamed: 0,name,phone,address,category_alias,category_title,rating,review_count,lat,lon
0,0,Strictly Automotive,1.303436e+10,"804 W 10th Ave Denver, CO 80204","autorepair, usedcardealers,","Auto Repair, Used Car Dealers,",4.5,138,39.731800,-104.997910
1,1,Les Schwab Tire Center,1.303456e+10,"2001 Federal Blvd Denver, CO 80211","tires, autorepair, oilchange,","Tires, Auto Repair, Oil Change Stations,",4.5,138,39.747720,-105.025456
2,2,Golden Triangle Auto Care,1.303573e+10,"1112 Speer Blvd Denver, CO 80204","autorepair, oilchange, transmissionrepair,","Auto Repair, Oil Change Stations, Transmission...",4.0,109,39.734052,-104.993612
3,3,Paddock Imports,1.303826e+10,"2400 W 7th Ave Denver, CO 80204","autorepair, autopartssupplies, tires,","Auto Repair, Auto Parts & Supplies, Tires,",4.5,117,39.727142,-105.016526
4,4,Auto Know How,1.303892e+10,"1240 Umatilla St Denver, CO 80204","autorepair,","Auto Repair,",4.5,56,39.735855,-105.012162

In [5]:
columns = ["FIRST_OCCURRENCE_DATE","LAST_OCCURRENCE_DATE","DISTRICT_ID", "PRECINCT_ID"]

In [6]:
auto_part_theft.drop(columns, axis=1, inplace=True)
auto

In [9]:
auto_part_theft.head()

,incident_id,offense_id,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,REPORTED_DATE,address,GEO_X,GEO_Y,lon,lat,NEIGHBORHOOD_ID,IS_CRIME,IS_TRAFFIC
0,20223421,2.022340e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/3/2022 10:47,4055 N ALBION ST ...,3157680,1707127,-104.939033,39.773534,northeast-park-hill,1,0
1,20226000117,2.022600e+16,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/3/2022 14:32,25 E 16TH AVE ...,3144402,1695493,-104.986504,39.741812,north-capitol-hill,1,0
2,20226673,2.022670e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/5/2022 11:26,2401 E 40TH AVE ...,3152270,1706837,-104.958285,39.772828,clayton,1,0
3,20228679,2.022870e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/6/2022 16:54,E 35TH AVE / N ALBION ST ...,3157620,1704248,-104.939309,39.765632,northeast-park-hill,1,0
4,20225711,2.022570e+13,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/4/2022 19:15,1830 N FRANKLIN ST ...,3149529,1696797,-104.968245,39.745311,city-park-west,1,0

In [17]:
coords_1 = (39.731800, -104.997910)
coords_2 = (39.773534, -104.939033)

print (geopy.distance.distance(coords_1, coords_2).km)

6.850674051338166