In [1]:
import pandas as pd
import requests
import json
from pprint import pprint
import time
from config import key

In [27]:
businesses_raw_df=pd.read_csv(r"C:\Users\vowel\Desktop\businesses_raw_df.csv")
businesses_raw_df.shape

(20920, 11)

In [19]:
businesses_raw_df.drop(['id'], axis=1, inplace=True)
businesses_raw_df.head()

,Unnamed: 0,name,phone,address,category_alias,category_title,rating,review_count,lat,lon
0,0,"Snooze, an A.M. Eatery",1.303297e+10,"2262 Larimer St Denver, CO 80205","breakfast_brunch, sandwiches, tradamerican,","Breakfast & Brunch, Sandwiches, American (Trad...",4.5,4511,39.755440,-104.988830
1,1,Rioja,1.303820e+10,"1431 Larimer St Denver, CO 80202","newamerican, spanish, bars,","American (New), Spanish, Bars,",4.5,2442,39.747808,-104.999331
2,2,Root Down,1.303993e+10,"1600 W 33rd Ave Denver, CO 80211","newamerican, vegan, vegetarian,","American (New), Vegan, Vegetarian,",4.5,3547,39.763060,-105.005600
3,3,"Snooze, an A.M. Eatery",1.303825e+10,"1701 Wynkoop St Ste 150 Denver, CO 80202","breakfast_brunch, sandwiches, tradamerican,","Breakfast & Brunch, Sandwiches, American (Trad...",4.5,1272,39.753417,-104.999892
4,4,Mercantile Dining & Provision,1.720460e+10,"1701 Wynkoop St Ste 155 Denver, CO 80202","newamerican,","American (New),",4.5,1196,39.753615,-104.999776

In [21]:
businesses_raw_df = businesses_raw_df.loc[:, ~businesses_raw_df.columns.str.contains('^Unnamed')]
businesses_raw_df.head()

,name,phone,address,category_alias,category_title,rating,review_count,lat,lon
0,"Snooze, an A.M. Eatery",1.303297e+10,"2262 Larimer St Denver, CO 80205","breakfast_brunch, sandwiches, tradamerican,","Breakfast & Brunch, Sandwiches, American (Trad...",4.5,4511,39.755440,-104.988830
1,Rioja,1.303820e+10,"1431 Larimer St Denver, CO 80202","newamerican, spanish, bars,","American (New), Spanish, Bars,",4.5,2442,39.747808,-104.999331
2,Root Down,1.303993e+10,"1600 W 33rd Ave Denver, CO 80211","newamerican, vegan, vegetarian,","American (New), Vegan, Vegetarian,",4.5,3547,39.763060,-105.005600
3,"Snooze, an A.M. Eatery",1.303825e+10,"1701 Wynkoop St Ste 150 Denver, CO 80202","breakfast_brunch, sandwiches, tradamerican,","Breakfast & Brunch, Sandwiches, American (Trad...",4.5,1272,39.753417,-104.999892
4,Mercantile Dining & Provision,1.720460e+10,"1701 Wynkoop St Ste 155 Denver, CO 80202","newamerican,","American (New),",4.5,1196,39.753615,-104.999776

In [22]:
businesses_raw_df.shape

(20920, 9)

In [23]:
businesses_raw_copy = businesses_raw_df.copy()

In [26]:
duplicateDFRow = businesses_raw_copy[businesses_raw_copy.duplicated()]
print(duplicateDFRow)

                             name         phone  \
1000             Angelo’s Taverna  1.303744e+10
1001                 City O' City  1.303832e+10
1002   Odyssey Italian Restaurant  1.303318e+10
1003                        Jelly  1.303832e+10
1004             Steuben's Uptown  1.303830e+10
...                           ...           ...
20912        Tortilleria San Juan  1.303366e+10
20913                   Starbucks  1.720532e+10
20916         Westerly Creek Park           NaN
20917      Fritay Haitian Cuisine  1.720736e+10
20918     Buddahs BBQ & Soul Food  1.720451e+10

                                                 address  \
1000                     620 E 6th Ave  Denver, CO 80203
1001                    206 E 13th Ave  Denver, CO 80203
1002                     603 E 6th Ave  Denver, CO 80203
1003                    600 E 13th Ave  Denver, CO 80203
1004                    523 E 17th Ave  Denver, CO 80203
...                                                  ...
20912         3133 Peoria St  Ste 207G  Aurora, CO 80010
20913  10406 Martin Luther King Blvd  King Sooper Den...
20916                  9200 E 26th Ave  Denver, CO 80202
20917                998 Sheridan Blvd  Denver, CO 80204
20918                                   Aurora, CO 80011

                                 category_alias  \
1000                   italian, seafood, bars,
1001    breakfast_brunch, vegan, tradamerican,
1002            sicilian, seafood, pastashops,
1003    newamerican, breakfast_brunch, coffee,
1004   diners, breakfast_brunch, cocktailbars,
...                                         ...
20912                                 mexican,
20913                                  coffee,
20916                                   parks,
20917                     foodtrucks, haitian,
20918               bbq, soulfood, foodtrucks,

                                          category_title  rating  \
1000                            Italian, Seafood, Bars,      4.5
1001   Breakfast & Brunch, Vegan, American (Tradition...     4.0
1002                    Sicilian, Seafood, Pasta Shops,      4.5
1003   American (New), Breakfast & Brunch, Coffee & T...     4.0
1004         Diners, Breakfast & Brunch, Cocktail Bars,      4.0
...                                                  ...     ...
20912                                          Mexican,      2.5
20913                                     Coffee & Tea,      4.0
20916                                            Parks,      4.0
20917                             Food Trucks, Haitian,      5.0
20918                 Barbeque, Soul Food, Food Trucks,      4.5

       review_count        lat         lon
1000           1344  39.725523 -104.979224
1001           2354  39.736723 -104.984684
1002           1079  39.725781 -104.979706
1003           1771  39.736734 -104.979646
1004           2964  39.743490 -104.980170
...             ...        ...         ...
20912             2  39.760978 -104.847740
20913             1  39.759589 -104.866368
20916             1  39.758127 -104.878300
20917             2  39.732690 -105.052690
20918             2  39.746440 -104.814810

[16307 rows x 9 columns]