In [1]:
# Initial imports.
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Load Data
loans_df = pd.read_csv('loans_df.csv', index_col = 'LoanNumber' )
loans_df

,Unnamed: 0,DateApproved,BorrowerName,BorrowerAddress,BorrowerZip,LoanStatusDate,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,...,Gender,Veteran,ForgivenessAmount,ForgivenessDate,category_title,rating,review_count,lat,lon,Yelp_Category
LoanNumber,,,,,,,,,,,,,,,,,,,,,
8728957203,0,4/28/2020,INTELLISOURCE,"1899 Wynkoop St, Ste 200",80202,6/17/2021,Paid in Full,24,7275742.00,7275742.00,...,Female Owned,Non-Veteran,7356987.79,6/11/2021,"Employment Agencies,",1.5,7,39.754760,-104.997910,Professional Services
8681407204,1,4/28/2020,PRIMESOURCE STAFFING,"10065 E Harvard Ave, Suite 230",80231,7/20/2021,Paid in Full,24,5906386.28,5906386.28,...,NaN,NaN,5971113.80,6/11/2021,"Employment Agencies,",1.0,1,39.726059,-104.983238,Professional Services
9826177105,2,4/15/2020,ALLY PRODUCTS,1635 W 13TH AVE,80204,9/28/2021,Paid in Full,24,5865500.00,5865500.00,...,Male Owned,Non-Veteran,5943869.60,8/11/2021,"Office Equipment, Business Consulting, IT Serv...",2.5,3,39.737240,-105.008310,Professional Services
2089597208,3,4/15/2020,DAVIS GRAHAM & STUBBS LLP,"1550 17th Street, Ste 500",80202,7/13/2021,Paid in Full,24,5114560.00,5114560.00,...,NaN,NaN,5173803.65,6/15/2021,"Lawyers,",3.0,2,39.751680,-104.998950,Professional Services
8574487102,4,4/15/2020,ORTHOPEDIC CENTERS OFORADO,8101 LOWRY BLVD,80230,9/25/2021,Paid in Full,24,3527000.00,3527000.00,...,NaN,NaN,3573732.75,8/9/2021,"Sports Medicine, Orthopedists,",1.0,4,39.717893,-104.895233,Health
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7810438506,1352,3/6/2021,5280 RESUMES,1320 S Forest Way,80222,NaN,Exemption 4,60,1327.00,1327.00,...,Female Owned,Non-Veteran,NaN,NaN,"Editorial Services,",5.0,9,39.675860,-104.922090,Professional Services
2773518503,1353,2/22/2021,SUNRISE HYPNOTHERAPY,8330 E Quincy Ave Apt F301,80237,3/4/2022,Paid in Full,60,1000.00,1000.00,...,NaN,NaN,1009.84,2/17/2022,"Counseling & Mental Health, Career Counseling,",5.0,5,39.598190,-104.903560,Professional Services
4250667310,1354,4/29/2020,SUNRISE HYPNOTHERAPY,8330 E Quincy Ave Apt F301,80237,3/9/2021,Paid in Full,24,1000.00,1000.00,...,NaN,NaN,1008.25,2/25/2021,"Counseling & Mental Health, Career Counseling,",5.0,5,39.598190,-104.903560,Professional Services
5634797307,1355,4/30/2020,METRO DENVER HYPNOTHERAPY,"3955 E Exposition Ave, # 501",80209,4/16/2021,Paid in Full,24,513.00,513.00,...,NaN,NaN,517.42,3/15/2021,"Hypnosis/Hypnotherapy, Counseling & Mental Hea...",5.0,3,39.705286,-104.941672,Health
3616317801,1356,5/26/2020,JACKSON ELITE TAX &SULTING,3425 E 28TH AVE,80205,5/18/2021,Paid in Full,24,500.00,500.00,...,NaN,NaN,504.65,4/29/2021,"Tax Services, Payroll Services, Business Consu...",5.0,1,39.757173,-104.946819,Financial Services

# Prep to Encode Data

In [4]:
# List all columns
loans_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1357 entries, 8728957203 to 3616317801
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1357 non-null   int64
 1   DateApproved            1357 non-null   object
 2   BorrowerName            1357 non-null   object
 3   BorrowerAddress         1357 non-null   object
 4   BorrowerZip             1357 non-null   int64
 5   LoanStatusDate          1238 non-null   object
 6   LoanStatus              1357 non-null   object
 7   Term                    1357 non-null   int64
 8   InitialApprovalAmount   1357 non-null   float64
 9   CurrentApprovalAmount   1357 non-null   float64
 10  BusinessAgeDescription  1294 non-null   object
 11  CD                      1357 non-null   object
 12  JobsReported            1357 non-null   float64
 13  Race                    299 non-null    object
 14  Ethnicity               367 non-null    object
 15  BusinessType            1357 non-null   object
 16  Gender                  489 non-null    object
 17  Veteran                 425 non-null    object
 18  ForgivenessAmount       1268 non-null   float64
 19  ForgivenessDate         1268 non-null   object
 20  category_title          1357 non-null   object
 21  rating                  1357 non-null   float64
 22  review_count            1357 non-null   int64
 23  lat                     1357 non-null   float64
 24  lon                     1357 non-null   float64
 25  Yelp_Category           1357 non-null   object
dtypes: float64(7), int64(4), object(15)
memory usage: 286.2+ KB

In [5]:
# Date - Split into month, day, year 
loans_df[['MonthApproved','DayApproved','YearApproved']] = loans_df.DateApproved.str.split('/',expand=True)
loans_df[['MonthApproved','DayApproved','YearApproved']]

           MonthApproved DayApproved YearApproved
LoanNumber
8728957203             4          28         2020
8681407204             4          28         2020
9826177105             4          15         2020
2089597208             4          15         2020
8574487102             4          15         2020
...                  ...         ...          ...
7810438506             3           6         2021
2773518503             2          22         2021
4250667310             4          29         2020
5634797307             4          30         2020
3616317801             5          26         2020

[1357 rows x 3 columns]

In [6]:
loans_df['BorrowerName'].duplicated().sum()

372

In [7]:
# 'BusinessAgeDescription' column - drop nulls
loans_df = loans_df.dropna(subset=['BusinessAgeDescription'])
loans_df

,Unnamed: 0,DateApproved,BorrowerName,BorrowerAddress,BorrowerZip,LoanStatusDate,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,...,ForgivenessDate,category_title,rating,review_count,lat,lon,Yelp_Category,MonthApproved,DayApproved,YearApproved
LoanNumber,,,,,,,,,,,,,,,,,,,,,
8728957203,0,4/28/2020,INTELLISOURCE,"1899 Wynkoop St, Ste 200",80202,6/17/2021,Paid in Full,24,7275742.0,7275742.0,...,6/11/2021,"Employment Agencies,",1.5,7,39.754760,-104.997910,Professional Services,4,28,2020
9826177105,2,4/15/2020,ALLY PRODUCTS,1635 W 13TH AVE,80204,9/28/2021,Paid in Full,24,5865500.0,5865500.0,...,8/11/2021,"Office Equipment, Business Consulting, IT Serv...",2.5,3,39.737240,-105.008310,Professional Services,4,15,2020
2089597208,3,4/15/2020,DAVIS GRAHAM & STUBBS LLP,"1550 17th Street, Ste 500",80202,7/13/2021,Paid in Full,24,5114560.0,5114560.0,...,6/15/2021,"Lawyers,",3.0,2,39.751680,-104.998950,Professional Services,4,15,2020
8574487102,4,4/15/2020,ORTHOPEDIC CENTERS OFORADO,8101 LOWRY BLVD,80230,9/25/2021,Paid in Full,24,3527000.0,3527000.0,...,8/9/2021,"Sports Medicine, Orthopedists,",1.0,4,39.717893,-104.895233,Health,4,15,2020
7218167001,5,4/7/2020,ARGUS EVENT STAFFING,4001 Fox Street,80216,NaN,Exemption 4,60,3230500.0,3230500.0,...,7/30/2021,"Employment Agencies,",1.0,1,39.771974,-104.995255,Professional Services,4,7,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7810438506,1352,3/6/2021,5280 RESUMES,1320 S Forest Way,80222,NaN,Exemption 4,60,1327.0,1327.0,...,NaN,"Editorial Services,",5.0,9,39.675860,-104.922090,Professional Services,3,6,2021
2773518503,1353,2/22/2021,SUNRISE HYPNOTHERAPY,8330 E Quincy Ave Apt F301,80237,3/4/2022,Paid in Full,60,1000.0,1000.0,...,2/17/2022,"Counseling & Mental Health, Career Counseling,",5.0,5,39.598190,-104.903560,Professional Services,2,22,2021
4250667310,1354,4/29/2020,SUNRISE HYPNOTHERAPY,8330 E Quincy Ave Apt F301,80237,3/9/2021,Paid in Full,24,1000.0,1000.0,...,2/25/2021,"Counseling & Mental Health, Career Counseling,",5.0,5,39.598190,-104.903560,Professional Services,4,29,2020
5634797307,1355,4/30/2020,METRO DENVER HYPNOTHERAPY,"3955 E Exposition Ave, # 501",80209,4/16/2021,Paid in Full,24,513.0,513.0,...,3/15/2021,"Hypnosis/Hypnotherapy, Counseling & Mental Hea...",5.0,3,39.705286,-104.941672,Health,4,30,2020
3616317801,1356,5/26/2020,JACKSON ELITE TAX &SULTING,3425 E 28TH AVE,80205,5/18/2021,Paid in Full,24,500.0,500.0,...,4/29/2021,"Tax Services, Payroll Services, Business Consu...",5.0,1,39.757173,-104.946819,Financial Services,5,26,2020

In [8]:
# 'BusinessAgeDescription' column - drop nulls
loans_df = loans_df.dropna(subset=['ForgivenessAmount'])
loans_df

,Unnamed: 0,DateApproved,BorrowerName,BorrowerAddress,BorrowerZip,LoanStatusDate,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,...,ForgivenessDate,category_title,rating,review_count,lat,lon,Yelp_Category,MonthApproved,DayApproved,YearApproved
LoanNumber,,,,,,,,,,,,,,,,,,,,,
8728957203,0,4/28/2020,INTELLISOURCE,"1899 Wynkoop St, Ste 200",80202,6/17/2021,Paid in Full,24,7275742.0,7275742.0,...,6/11/2021,"Employment Agencies,",1.5,7,39.754760,-104.997910,Professional Services,4,28,2020
9826177105,2,4/15/2020,ALLY PRODUCTS,1635 W 13TH AVE,80204,9/28/2021,Paid in Full,24,5865500.0,5865500.0,...,8/11/2021,"Office Equipment, Business Consulting, IT Serv...",2.5,3,39.737240,-105.008310,Professional Services,4,15,2020
2089597208,3,4/15/2020,DAVIS GRAHAM & STUBBS LLP,"1550 17th Street, Ste 500",80202,7/13/2021,Paid in Full,24,5114560.0,5114560.0,...,6/15/2021,"Lawyers,",3.0,2,39.751680,-104.998950,Professional Services,4,15,2020
8574487102,4,4/15/2020,ORTHOPEDIC CENTERS OFORADO,8101 LOWRY BLVD,80230,9/25/2021,Paid in Full,24,3527000.0,3527000.0,...,8/9/2021,"Sports Medicine, Orthopedists,",1.0,4,39.717893,-104.895233,Health,4,15,2020
7218167001,5,4/7/2020,ARGUS EVENT STAFFING,4001 Fox Street,80216,NaN,Exemption 4,60,3230500.0,3230500.0,...,7/30/2021,"Employment Agencies,",1.0,1,39.771974,-104.995255,Professional Services,4,7,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5431627705,1351,5/1/2020,COMPLETE WELLNESS CHIROPRACTIC,1777 S BELLAIRE ST STE G125,80222,8/19/2021,Paid in Full,24,1395.0,1395.0,...,7/9/2021,"Chiropractors, Physical Therapy, Nutritionists,",5.0,8,39.684343,-104.937757,Health,5,1,2020
2773518503,1353,2/22/2021,SUNRISE HYPNOTHERAPY,8330 E Quincy Ave Apt F301,80237,3/4/2022,Paid in Full,60,1000.0,1000.0,...,2/17/2022,"Counseling & Mental Health, Career Counseling,",5.0,5,39.598190,-104.903560,Professional Services,2,22,2021
4250667310,1354,4/29/2020,SUNRISE HYPNOTHERAPY,8330 E Quincy Ave Apt F301,80237,3/9/2021,Paid in Full,24,1000.0,1000.0,...,2/25/2021,"Counseling & Mental Health, Career Counseling,",5.0,5,39.598190,-104.903560,Professional Services,4,29,2020
5634797307,1355,4/30/2020,METRO DENVER HYPNOTHERAPY,"3955 E Exposition Ave, # 501",80209,4/16/2021,Paid in Full,24,513.0,513.0,...,3/15/2021,"Hypnosis/Hypnotherapy, Counseling & Mental Hea...",5.0,3,39.705286,-104.941672,Health,4,30,2020
3616317801,1356,5/26/2020,JACKSON ELITE TAX &SULTING,3425 E 28TH AVE,80205,5/18/2021,Paid in Full,24,500.0,500.0,...,4/29/2021,"Tax Services, Payroll Services, Business Consu...",5.0,1,39.757173,-104.946819,Financial Services,5,26,2020

In [9]:
# Drop unneeded columns
loans_df.drop(columns=['Unnamed: 0', 'DateApproved','LoanStatusDate', 'ForgivenessDate','DayApproved','BorrowerAddress',
                       'category_title'], inplace=True)
loans_df.head(10)

,BorrowerName,BorrowerZip,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,BusinessAgeDescription,CD,JobsReported,Race,...,Gender,Veteran,ForgivenessAmount,rating,review_count,lat,lon,Yelp_Category,MonthApproved,YearApproved
LoanNumber,,,,,,,,,,,,,,,,,,,,,
8728957203,INTELLISOURCE,80202,Paid in Full,24,7275742.0,7275742.0,Existing or more than 2 years old,CO-01,500.0,White,...,Female Owned,Non-Veteran,7356987.79,1.5,7,39.754760,-104.997910,Professional Services,4,2020
9826177105,ALLY PRODUCTS,80204,Paid in Full,24,5865500.0,5865500.0,Existing or more than 2 years old,CO-01,391.0,White,...,Male Owned,Non-Veteran,5943869.60,2.5,3,39.737240,-105.008310,Professional Services,4,2020
2089597208,DAVIS GRAHAM & STUBBS LLP,80202,Paid in Full,24,5114560.0,5114560.0,Existing or more than 2 years old,CO-01,227.0,NaN,...,NaN,NaN,5173803.65,3.0,2,39.751680,-104.998950,Professional Services,4,2020
8574487102,ORTHOPEDIC CENTERS OFORADO,80230,Paid in Full,24,3527000.0,3527000.0,Existing or more than 2 years old,CO-01,249.0,NaN,...,NaN,NaN,3573732.75,1.0,4,39.717893,-104.895233,Health,4,2020
7218167001,ARGUS EVENT STAFFING,80216,Exemption 4,60,3230500.0,3230500.0,Existing or more than 2 years old,CO-01,500.0,NaN,...,NaN,NaN,971592.57,1.0,1,39.771974,-104.995255,Professional Services,4,2020
8400557001,ENSCICONPORATION,80211,Paid in Full,24,2734353.0,2734353.0,Existing or more than 2 years old,CO-01,151.0,NaN,...,NaN,NaN,2766865.58,5.0,3,39.753910,-105.016720,Professional Services,4,2020
9123038501,ENSCICONPORATION,80211,Paid in Full,60,2000000.0,2000000.0,Existing or more than 2 years old,CO-01,237.0,NaN,...,NaN,NaN,2007452.05,5.0,3,39.753910,-105.016720,Professional Services,3,2021
2487277702,OPTIMAL HOME CARE,80237,Paid in Full,24,2315912.0,2315912.0,Existing or more than 2 years old,CO-01,181.0,NaN,...,Male Owned,Non-Veteran,2341444.93,3.0,5,39.637339,-104.898715,Health,5,2020
4952518508,OPTIMAL HOME CARE,80237,Paid in Full,60,2000000.0,2000000.0,Existing or more than 2 years old,CO-01,193.0,White,...,Male Owned,Non-Veteran,2017260.27,3.0,5,39.637339,-104.898715,Health,2,2021
7672377005,SEATTLE FISHPANY,80216,Paid in Full,24,2205500.0,2205500.0,Existing or more than 2 years old,CO-01,181.0,NaN,...,NaN,NaN,2231230.83,3.0,2,39.774870,-104.915680,Restaurants,4,2020

In [10]:
# Create new df with info
info_df = loans_df[['BorrowerName','Race','Ethnicity','Gender','Veteran']]
info_df

,BorrowerName,Race,Ethnicity,Gender,Veteran
LoanNumber,,,,,
8728957203,INTELLISOURCE,White,Not Hispanic or Latino,Female Owned,Non-Veteran
9826177105,ALLY PRODUCTS,White,Not Hispanic or Latino,Male Owned,Non-Veteran
2089597208,DAVIS GRAHAM & STUBBS LLP,NaN,NaN,NaN,NaN
8574487102,ORTHOPEDIC CENTERS OFORADO,NaN,NaN,NaN,NaN
7218167001,ARGUS EVENT STAFFING,NaN,NaN,NaN,NaN
...,...,...,...,...,...
5431627705,COMPLETE WELLNESS CHIROPRACTIC,NaN,NaN,NaN,NaN
2773518503,SUNRISE HYPNOTHERAPY,NaN,NaN,NaN,NaN
4250667310,SUNRISE HYPNOTHERAPY,NaN,NaN,NaN,NaN
5634797307,METRO DENVER HYPNOTHERAPY,NaN,NaN,NaN,NaN
3616317801,JACKSON ELITE TAX &SULTING,NaN,NaN,NaN,NaN

In [11]:
loans_df.drop(columns=['BorrowerName','Race','Ethnicity','Gender','Veteran'], inplace=True)
loans_df.head(10)

,BorrowerZip,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,BusinessAgeDescription,CD,JobsReported,BusinessType,ForgivenessAmount,rating,review_count,lat,lon,Yelp_Category,MonthApproved,YearApproved
LoanNumber,,,,,,,,,,,,,,,,,
8728957203,80202,Paid in Full,24,7275742.0,7275742.0,Existing or more than 2 years old,CO-01,500.0,Limited Liability Company(LLC),7356987.79,1.5,7,39.754760,-104.997910,Professional Services,4,2020
9826177105,80204,Paid in Full,24,5865500.0,5865500.0,Existing or more than 2 years old,CO-01,391.0,Corporation,5943869.60,2.5,3,39.737240,-105.008310,Professional Services,4,2020
2089597208,80202,Paid in Full,24,5114560.0,5114560.0,Existing or more than 2 years old,CO-01,227.0,Partnership,5173803.65,3.0,2,39.751680,-104.998950,Professional Services,4,2020
8574487102,80230,Paid in Full,24,3527000.0,3527000.0,Existing or more than 2 years old,CO-01,249.0,Limited Liability Company(LLC),3573732.75,1.0,4,39.717893,-104.895233,Health,4,2020
7218167001,80216,Exemption 4,60,3230500.0,3230500.0,Existing or more than 2 years old,CO-01,500.0,Limited Liability Company(LLC),971592.57,1.0,1,39.771974,-104.995255,Professional Services,4,2020
8400557001,80211,Paid in Full,24,2734353.0,2734353.0,Existing or more than 2 years old,CO-01,151.0,Corporation,2766865.58,5.0,3,39.753910,-105.016720,Professional Services,4,2020
9123038501,80211,Paid in Full,60,2000000.0,2000000.0,Existing or more than 2 years old,CO-01,237.0,Corporation,2007452.05,5.0,3,39.753910,-105.016720,Professional Services,3,2021
2487277702,80237,Paid in Full,24,2315912.0,2315912.0,Existing or more than 2 years old,CO-01,181.0,Sole Proprietorship,2341444.93,3.0,5,39.637339,-104.898715,Health,5,2020
4952518508,80237,Paid in Full,60,2000000.0,2000000.0,Existing or more than 2 years old,CO-01,193.0,Sole Proprietorship,2017260.27,3.0,5,39.637339,-104.898715,Health,2,2021
7672377005,80216,Paid in Full,24,2205500.0,2205500.0,Existing or more than 2 years old,CO-01,181.0,Corporation,2231230.83,3.0,2,39.774870,-104.915680,Restaurants,4,2020

In [12]:
loans_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1207 entries, 8728957203 to 3616317801
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   BorrowerZip             1207 non-null   int64
 1   LoanStatus              1207 non-null   object
 2   Term                    1207 non-null   int64
 3   InitialApprovalAmount   1207 non-null   float64
 4   CurrentApprovalAmount   1207 non-null   float64
 5   BusinessAgeDescription  1207 non-null   object
 6   CD                      1207 non-null   object
 7   JobsReported            1207 non-null   float64
 8   BusinessType            1207 non-null   object
 9   ForgivenessAmount       1207 non-null   float64
 10  rating                  1207 non-null   float64
 11  review_count            1207 non-null   int64
 12  lat                     1207 non-null   float64
 13  lon                     1207 non-null   float64
 14  Yelp_Category           1207 non-null   object
 15  MonthApproved           1207 non-null   object
 16  YearApproved            1207 non-null   object
dtypes: float64(7), int64(3), object(7)
memory usage: 169.7+ KB

# Encode Data and save to csv

In [13]:
# Encode using get_dummies method
encoded_loans_df = pd.get_dummies(loans_df, columns=['BusinessAgeDescription', 'CD','BusinessType',
                                                     'Yelp_Category', 'MonthApproved','YearApproved'])
encoded_loans_df

,BorrowerZip,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,JobsReported,ForgivenessAmount,rating,review_count,lat,...,MonthApproved_1,MonthApproved_2,MonthApproved_3,MonthApproved_4,MonthApproved_5,MonthApproved_6,MonthApproved_7,MonthApproved_8,YearApproved_2020,YearApproved_2021
LoanNumber,,,,,,,,,,,,,,,,,,,,,
8728957203,80202,Paid in Full,24,7275742.0,7275742.0,500.0,7356987.79,1.5,7,39.754760,...,0,0,0,1,0,0,0,0,1,0
9826177105,80204,Paid in Full,24,5865500.0,5865500.0,391.0,5943869.60,2.5,3,39.737240,...,0,0,0,1,0,0,0,0,1,0
2089597208,80202,Paid in Full,24,5114560.0,5114560.0,227.0,5173803.65,3.0,2,39.751680,...,0,0,0,1,0,0,0,0,1,0
8574487102,80230,Paid in Full,24,3527000.0,3527000.0,249.0,3573732.75,1.0,4,39.717893,...,0,0,0,1,0,0,0,0,1,0
7218167001,80216,Exemption 4,60,3230500.0,3230500.0,500.0,971592.57,1.0,1,39.771974,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5431627705,80222,Paid in Full,24,1395.0,1395.0,2.0,1411.43,5.0,8,39.684343,...,0,0,0,0,1,0,0,0,1,0
2773518503,80237,Paid in Full,60,1000.0,1000.0,1.0,1009.84,5.0,5,39.598190,...,0,1,0,0,0,0,0,0,0,1
4250667310,80237,Paid in Full,24,1000.0,1000.0,1.0,1008.25,5.0,5,39.598190,...,0,0,0,1,0,0,0,0,1,0
5634797307,80209,Paid in Full,24,513.0,513.0,1.0,517.42,5.0,3,39.705286,...,0,0,0,1,0,0,0,0,1,0
3616317801,80205,Paid in Full,24,500.0,500.0,1.0,504.65,5.0,1,39.757173,...,0,0,0,0,1,0,0,0,1,0

In [14]:
# Save encoded and info dfs to csvs
encoded_loans_df.to_csv('encoded_loans_dfV2.0.csv')
info_df.to_csv('info_df.csv')