 # Predicting Diabetes

In [1]:
from path import Path
import pandas as pd

In [2]:
data = Path(r"C:\Users\vowel\Downloads\encoded_loans_dfV2.0.csv")
df = pd.read_csv(data)
df.head()

,LoanNumber,BorrowerZip,LoanStatus,Term,InitialApprovalAmount,CurrentApprovalAmount,JobsReported,ForgivenessAmount,rating,review_count,...,MonthApproved_1,MonthApproved_2,MonthApproved_3,MonthApproved_4,MonthApproved_5,MonthApproved_6,MonthApproved_7,MonthApproved_8,YearApproved_2020,YearApproved_2021
0,8728957203,80202,Paid in Full,24,7275742.0,7275742.0,500.0,7356987.79,1.5,7,...,0,0,0,1,0,0,0,0,1,0
1,9826177105,80204,Paid in Full,24,5865500.0,5865500.0,391.0,5943869.60,2.5,3,...,0,0,0,1,0,0,0,0,1,0
2,2089597208,80202,Paid in Full,24,5114560.0,5114560.0,227.0,5173803.65,3.0,2,...,0,0,0,1,0,0,0,0,1,0
3,8574487102,80230,Paid in Full,24,3527000.0,3527000.0,249.0,3573732.75,1.0,4,...,0,0,0,1,0,0,0,0,1,0
4,7218167001,80216,Exemption 4,60,3230500.0,3230500.0,500.0,971592.57,1.0,1,...,0,0,0,1,0,0,0,0,1,0

 ## Separate the Features (X) from the Target (y)

In [3]:
y = df["LoanStatus"]
X = df.drop(columns="LoanStatus")

 ## Split our data into training and testing

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1, 
                                                    stratify=y)
X_train.shape

(905, 46)

 ## Create a Logistic Regression Model

In [5]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs',
                                max_iter=200,
                                random_state=1)

 ## Fit (train) or model using the training data

In [6]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=200, random_state=1)

 ## Make predictions

In [7]:
y_pred = classifier.predict(X_test)
results = pd.DataFrame({"Prediction": y_pred, "Actual": y_test}).reset_index(drop=True)
results.head(20)

      Prediction        Actual
0   Paid in Full  Paid in Full
1   Paid in Full  Paid in Full
2   Paid in Full  Paid in Full
3   Paid in Full  Paid in Full
4   Paid in Full  Paid in Full
5   Paid in Full  Paid in Full
6   Paid in Full  Paid in Full
7   Paid in Full  Paid in Full
8   Paid in Full  Paid in Full
9   Paid in Full  Paid in Full
10  Paid in Full  Paid in Full
11  Paid in Full  Paid in Full
12  Paid in Full  Paid in Full
13  Paid in Full  Paid in Full
14  Paid in Full  Paid in Full
15  Paid in Full  Paid in Full
16  Paid in Full   Exemption 4
17  Paid in Full  Paid in Full
18  Paid in Full  Paid in Full
19  Paid in Full  Paid in Full

In [8]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.9735099337748344